os: osx
language: objective-c
osx_image: xcode9

before_script:
  - carthage version
  - carthage bootstrap

script: 
  - set -o pipefail
  - xcodebuild test -workspace Action.xcworkspace -scheme Action -sdk iphonesimulator -destination "name=iPhone X" | xcpretty -c
  - xcodebuild build  -workspace Action.xcworkspace -scheme Action-watchOS -sdk watchsimulator -destination "name=Apple Watch - 38mm" | xcpretty -c
  - xcodebuild build -workspace Action.xcworkspace -scheme Action-macOS -sdk macosx -destination "arch=x86_64" | xcpretty -c
  - xcodebuild build -workspace Action.xcworkspace -scheme Action-tvOS -sdk appletvsimulator -destination "name=Apple TV 1080p" | xcpretty -c

